# bitbucket-pipelines.yml (build & run con Docker)
image: docker:24.0

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build image & run tests in container
        services: [docker]
        script:
          # Construir la imagen con el Dockerfile del repo
          - DOCKER_BUILDKIT=1 docker build -t serenity-chrome:ci .

          # Caché de Maven dentro del workspace (se persistirá como artifacts si quieres)
          - mkdir -p .m2

          # Ejecutar los tests dentro del contenedor, montando el repo
          - docker run --rm \
              -v "$BITBUCKET_CLONE_DIR":/workspace \
              -v "$BITBUCKET_CLONE_DIR/.m2":/root/.m2 \
              -w /workspace \
              -e MAVEN_OPTS="-Dmaven.repo.local=/root/.m2" \
              serenity-chrome:ci \
              bash -lc '
                export BASE_URL="https://www.saucedemo.com/";
                mvn -B clean test \
                  -Dserenity.configuration=serenity-ci.properties \
                  -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
                  -Dwebdriver.base.url="$BASE_URL" \
                  -e -Dsurefire.printSummary=true;
                mvn -B serenity:aggregate
              '

        artifacts:
          - target/site/serenity/**
          - target/serenity/**
          - target/screenshots/**
