image: docker:24.0
options: { docker: true }

pipelines:
  default:
    - step:
        name: Build image & run tests in container
        services: [docker]
        script:
          - export DOCKER_BUILDKIT=0
          - docker build -t serenity-chrome:ci .
          - mkdir -p .m2
          - |
            docker run --rm --shm-size=2g \
              -v "$BITBUCKET_CLONE_DIR":/workspace \
              -v "$BITBUCKET_CLONE_DIR/.m2":/root/.m2 \
              -w /workspace \
              -e MAVEN_OPTS=-Dmaven.repo.local=/root/.m2 \
              serenity-chrome:ci \
              bash -lc '
                set -euxo pipefail
                which google-chrome; google-chrome --version
                which chromedriver; chromedriver --version

                # Pre-check del driver: debe responder JSON con "ready":true
                chromedriver --port=9515 > target/chromedriver-boot.log 2>&1 &
                sleep 2
                curl -s http://127.0.0.1:9515/status | tee target/chromedriver-status.json

                export BASE_URL="https://www.saucedemo.com/"
                mvn -B clean test \
                  -Dserenity.configuration=serenity-ci.properties \
                  -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
                  -Dwebdriver.base.url="$BASE_URL" \
                  "-Dchrome.switches=--headless=new,--no-sandbox,--disable-dev-shm-usage,--remote-allow-origins=*,--window-size=1920,1080" \
                  -Dwebdriver.chrome.verboseLogging=true \
                  -e -Dsurefire.printSummary=true

                mvn -B serenity:aggregate
              '
        artifacts:
          - target/site/serenity/**
          - target/serenity/**
          - target/screenshots/**
          - target/chromedriver.log
          - target/chromedriver-boot.log
          - target/chromedriver-status.json
