image: maven:3.9.6-eclipse-temurin-17

pipelines:
  default:
    - step:
        name: UI Tests
        caches: [maven]
        script:
          - apt-get update && apt-get install -y wget unzip curl gnupg
          - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          - apt-get install -y ./google-chrome-stable_current_amd64.deb || apt-get -f install -y
          - CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9.]+' | head -1 | cut -d'.' -f1)
          - VER=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION}")
          - wget -O /tmp/cd.zip "https://storage.googleapis.com/chrome-for-testing-public/${VER}/linux64/chromedriver-linux64.zip"
          - unzip -o /tmp/cd.zip -d /tmp
          - mkdir -p drivers && mv /tmp/chromedriver-linux64/chromedriver drivers/ && chmod +x drivers/chromedriver
          - google-chrome --version && drivers/chromedriver --version
          - >
            mvn -B clean test
            -Dwebdriver.chrome.driver="$(pwd)/drivers/chromedriver"
            -Dchrome.switches="--headless=new,--no-sandbox,--disable-dev-shm-usage,--window-size=1920,1080"
          - mvn -B serenity:aggregate
        artifacts:
          - target/serenity/**
          - target/screenshots/**
